import Foundation

// Generated from executed immutable-v9 registry/TNT/Juice warmup owners.
nonisolated enum NativeMeterSelectedWarmupCatalog {
 static func plan(special:String,variant:String?)->NativeMeterSelectedWarmupPlan? {
  switch variant ?? special {
  case "wild":return .init(selection:"wild",preOpen:[],committed:[])
  case "wild-juice":return .init(selection:"wild-juice",preOpen:[],committed:[NativeMeterWarmupAsset(["./assets/shop/juice/bubbles pack/bubble1.png"]),NativeMeterWarmupAsset(["./assets/shop/juice/bubbles pack/bubble 2.png"]),NativeMeterWarmupAsset(["./assets/shop/juice/bubbles pack/bubble 3.png"]),NativeMeterWarmupAsset(["./assets/shop/juice/bubbles pack/bubble 4.png"]),NativeMeterWarmupAsset(["./assets/shop/juice/bubbles pack/bubble 5.png"]),NativeMeterWarmupAsset(["./assets/shop/juice/bubbles pack/bubble 6.png"]),NativeMeterWarmupAsset(["./assets/shop/juice/bubbles pack/bubble 7.png"]),NativeMeterWarmupAsset(["./assets/shop/juice/bubbles pack/bubble 8.png"])])
  case "wild-magnet":return .init(selection:"wild-magnet",preOpen:[],committed:[])
  case "wild-tnt":return .init(selection:"wild-tnt",preOpen:[NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt1@2x.png", "./assets/shop/explosion pack/animation/tnt1.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt2@2x.png", "./assets/shop/explosion pack/animation/tnt2.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt3@2x.png", "./assets/shop/explosion pack/animation/tnt3.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt4@2x.png", "./assets/shop/explosion pack/animation/tnt4.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt5@2x.png", "./assets/shop/explosion pack/animation/tnt5.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt6@2x.png", "./assets/shop/explosion pack/animation/tnt6.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt7@2x.png", "./assets/shop/explosion pack/animation/tnt7.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt8@2x.png", "./assets/shop/explosion pack/animation/tnt8.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt9@2x.png", "./assets/shop/explosion pack/animation/tnt9.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt10@2x.png", "./assets/shop/explosion pack/animation/tnt10.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt11@2x.png", "./assets/shop/explosion pack/animation/tnt11.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt12@2x.png", "./assets/shop/explosion pack/animation/tnt12.png"])],committed:[])
  case "fish":return .init(selection:"fish",preOpen:[],committed:[])
  case "kanta":return .init(selection:"kanta",preOpen:[],committed:[])
  case "bee":return .init(selection:"bee",preOpen:[],committed:[])
  case "laser-gun":return .init(selection:"laser-gun",preOpen:[NativeMeterWarmupAsset(["./assets/shop/gun/lasergun1@2x.png"]),NativeMeterWarmupAsset(["./assets/shop/gun/lasergun2@2x.png"]),NativeMeterWarmupAsset(["./assets/shop/gun/lasergun3@2x.png"]),NativeMeterWarmupAsset(["./assets/shop/gun/lasergun4@2x.png"]),NativeMeterWarmupAsset(["./assets/shop/gun/lasergun5@2x.png"]),NativeMeterWarmupAsset(["./assets/shop/gun/lasergun6@2x.png"]),NativeMeterWarmupAsset(["./assets/shop/gun/left laser@2x.png"]),NativeMeterWarmupAsset(["./assets/shop/gun/right laser@2x.png"])],committed:[])
  case "spaceship":return .init(selection:"spaceship",preOpen:[],committed:[])
  case "bottle":return .init(selection:"bottle",preOpen:[],committed:[])
  case "honey":return .init(selection:"honey",preOpen:[],committed:[])
  case "flower":return .init(selection:"flower",preOpen:[NativeMeterWarmupAsset(["./assets/shop/bush/bush1.png"]),NativeMeterWarmupAsset(["./assets/shop/bush/bush2.png"]),NativeMeterWarmupAsset(["./assets/shop/bush/bush3.png"]),NativeMeterWarmupAsset(["./assets/shop/bush/bush4.png"]),NativeMeterWarmupAsset(["./assets/shop/bush/bush5.png"]),NativeMeterWarmupAsset(["./assets/shop/bush/bush6.png"]),NativeMeterWarmupAsset(["./assets/shop/bush/bush7.png"]),NativeMeterWarmupAsset(["./assets/shop/bush/bush8.png"]),NativeMeterWarmupAsset(["./assets/shop/bush/bush9.png"]),NativeMeterWarmupAsset(["./assets/shop/bush/flowr1.png"]),NativeMeterWarmupAsset(["./assets/shop/bush/flowr2.png"]),NativeMeterWarmupAsset(["./assets/shop/bush/flowr3.png"]),NativeMeterWarmupAsset(["./assets/shop/bush/flowr4.png"]),NativeMeterWarmupAsset(["./assets/shop/bush/flowr5.png"]),NativeMeterWarmupAsset(["./assets/shop/bush/flowr6.png"])],committed:[])
  case "barell":return .init(selection:"barell",preOpen:[NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt1@2x.png", "./assets/shop/explosion pack/animation/tnt1.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt2@2x.png", "./assets/shop/explosion pack/animation/tnt2.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt3@2x.png", "./assets/shop/explosion pack/animation/tnt3.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt4@2x.png", "./assets/shop/explosion pack/animation/tnt4.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt5@2x.png", "./assets/shop/explosion pack/animation/tnt5.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt6@2x.png", "./assets/shop/explosion pack/animation/tnt6.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt7@2x.png", "./assets/shop/explosion pack/animation/tnt7.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt8@2x.png", "./assets/shop/explosion pack/animation/tnt8.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt9@2x.png", "./assets/shop/explosion pack/animation/tnt9.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt10@2x.png", "./assets/shop/explosion pack/animation/tnt10.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt11@2x.png", "./assets/shop/explosion pack/animation/tnt11.png"]),NativeMeterWarmupAsset(["./assets/shop/explosion pack/animation/tnt12@2x.png", "./assets/shop/explosion pack/animation/tnt12.png"]),NativeMeterWarmupAsset(["./assets/shop/barell/wood1.png"]),NativeMeterWarmupAsset(["./assets/shop/barell/wood2.png"]),NativeMeterWarmupAsset(["./assets/shop/barell/wood3.png"]),NativeMeterWarmupAsset(["./assets/shop/barell/wood4.png"]),NativeMeterWarmupAsset(["./assets/shop/barell/wood5.png"]),NativeMeterWarmupAsset(["./assets/shop/barell/wood6.png"])],committed:[])
  case "mushroom":return .init(selection:"mushroom",preOpen:[],committed:[NativeMeterWarmupAsset(["./assets/shop/mushroom/mushroom@2x.png"]),NativeMeterWarmupAsset(["./assets/shop/mushroom/mushroom1.png"]),NativeMeterWarmupAsset(["./assets/shop/mushroom/mushroom2.png"]),NativeMeterWarmupAsset(["./assets/shop/mushroom/mushroom3.png"]),NativeMeterWarmupAsset(["./assets/shop/mushroom/mushroom4.png"]),NativeMeterWarmupAsset(["./assets/shop/mushroom/mushroom5.png"])])
  case "robo-cube":return .init(selection:"robo-cube",preOpen:[],committed:[NativeMeterWarmupAsset(["./assets/shop/robo/robo1.png"]),NativeMeterWarmupAsset(["./assets/shop/robo/robo2.png"]),NativeMeterWarmupAsset(["./assets/shop/robo/robo3.png"]),NativeMeterWarmupAsset(["./assets/shop/robo/robo4.png"]),NativeMeterWarmupAsset(["./assets/shop/robo/robo5.png"]),NativeMeterWarmupAsset(["./assets/shop/robo/robo6.png"]),NativeMeterWarmupAsset(["./assets/shop/robo/robo7.png"]),NativeMeterWarmupAsset(["./assets/shop/robo/robo8.png"]),NativeMeterWarmupAsset(["./assets/shop/robo/robo9.png"]),NativeMeterWarmupAsset(["./assets/shop/robo/robo10.png"]),NativeMeterWarmupAsset(["./assets/shop/robo/robo11.png"]),NativeMeterWarmupAsset(["./assets/shop/robo/robo12.png"]),NativeMeterWarmupAsset(["./assets/shop/robo/neon1.png"]),NativeMeterWarmupAsset(["./assets/shop/robo/neon2.png"]),NativeMeterWarmupAsset(["./assets/shop/robo/neon3.png"]),NativeMeterWarmupAsset(["./assets/shop/robo/neon4.png"])])
  case "cubero":return .init(selection:"cubero",preOpen:[],committed:[])
  case "beach-ball":return .init(selection:"beach-ball",preOpen:[NativeMeterWarmupAsset(["./assets/shop/ball/ball1.png"]),NativeMeterWarmupAsset(["./assets/shop/ball/ball2.png"]),NativeMeterWarmupAsset(["./assets/shop/ball/ball3.png"]),NativeMeterWarmupAsset(["./assets/shop/ball/ball4.png"]),NativeMeterWarmupAsset(["./assets/shop/ball/ball5.png"]),NativeMeterWarmupAsset(["./assets/shop/ball/ball6.png"])],committed:[NativeMeterWarmupAsset(["./assets/shop/ball/ball1.png"]),NativeMeterWarmupAsset(["./assets/shop/ball/ball2.png"]),NativeMeterWarmupAsset(["./assets/shop/ball/ball3.png"]),NativeMeterWarmupAsset(["./assets/shop/ball/ball4.png"]),NativeMeterWarmupAsset(["./assets/shop/ball/ball5.png"]),NativeMeterWarmupAsset(["./assets/shop/ball/ball6.png"])])
  default:return nil
  }
 }
}
