import fs from 'node:fs';import {fileURLToPath}from'node:url';const repo=fileURLToPath(new URL('../../',import.meta.url));const out=fileURLToPath(new URL('./',import.meta.url));import vm from 'node:vm';import {createRequire}from'node:module';const require=createRequire(import.meta.url),ts=require(repo+'/node_modules/typescript'),gsap=require(repo+'/node_modules/gsap/dist/gsap').gsap;
const root=repo,source=fs.readFileSync(root+'/src/modules/fx.ts','utf8'),ast=ts.createSourceFile('fx',source,ts.ScriptTarget.Latest,true),functions=['regularMerge6ShardsTemplated','smokeBubblesAtTile','showMultiplierTile','screenShake'];const original=ast.statements.filter(n=>ts.isFunctionDeclaration(n)&&functions.includes(n.name?.text)).map(n=>n.getText()).join('\n');
const fp=ts.createSourceFile('profile',fs.readFileSync(root+'/src/modules/gameplay-fx-profile.ts','utf8'),ts.ScriptTarget.Latest,true),helpers=fp.statements.filter(n=>ts.isFunctionDeclaration(n)&&['getOrganicRadialSmokeLayout','getSmokeCloudParticleAlpha','getRegularMerge6FxProfile'].includes(n.name?.text)).map(n=>n.getText()).join('\n');
const templateBox={exports:{}};vm.createContext(templateBox);vm.runInContext(ts.transpileModule(fs.readFileSync(root+'/src/modules/templates/wooden-template.js','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,templateBox);const template=templateBox.exports.default;
class Container{constructor(){this.x=0;this.y=0;this.rotation=0;this.alpha=1;this.scale={x:1,y:1,set(x,y=x){this.x=x;this.y=y}};this.children=[];this.destroyed=false}addChild(c){c.parent=this;this.children.push(c);return c}addChildAt(c,i){c.parent=this;this.children.splice(i,0,c);return c}removeChild(c){this.children=this.children.filter(x=>x!==c);c.parent=null}sortChildren(){}destroy(){this.destroyed=true}}
class Graphics extends Container{clear(){return this}poly(points){this.shape={type:'polygon',points};return this}circle(x,y,r){this.shape={type:'ellipse',rx:r,ry:r};return this}ellipse(x,y,rx,ry){this.shape={type:'ellipse',rx,ry};return this}fill(style){this.shape.fill=style;return this}stroke(style){this.shape.stroke=style;return this}updateBounds(){}}
class Text extends Container{constructor(options){super();this.options=options;this.anchor={set(){}}}}
let rows=[];
for(const initiallyShaken of [false,true])for(const pattern of [0,1,2])for(const reduced of [false,true])for(const [size,hot]of [[96,1],[128,.55],[180,.82]]) {
 let seed=7+pattern*19+(reduced?41:0)+size,draws=0,timelines=[],ttl=[];const random=()=>{draws++;seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};const math=Object.create(Math);math.random=random;
 const initialShake=initiallyShaken?[-1.3,2.8,-.7,1.1,-.4,.5]:[0,0,0,0,0,0];
 const board=new Container(),canvas={x:initialShake[0],y:initialShake[1],scale:1},indicator={x:initialShake[2],y:initialShake[3]},decor={x:initialShake[4],y:initialShake[5],hasAttribute:()=>false};const box={exports:{},console,Math:math,Container,Graphics,Text,gsap,setTimeout:(cb,time)=>{ttl.push(time/1000);return ttl.length},attachFxContainerActivity(){},releaseFxContainerActivity(){},isVerboseGameplayLogsEnabled:()=>false,getParams:()=>template.params.regular,getColor:()=>template.colors.regular,selectPattern:()=>({patternName:template.patternMap.regular[pattern],patternData:template.patterns[template.patternMap.regular[pattern]],pool:{acquire:()=>new Graphics(),release(){}}}),graphicsPool:{acquire:()=>new Graphics(),release(){}},centerInBoard:()=>({x:0,y:0}),getFxHotFactor:()=>hot,autoAdd:(parent,child,time)=>{parent.addChild(child);ttl.push(time)},trackTween:(target,vars)=>{const t=gsap.to(target,vars).pause();t._sourceDelay=vars.delay??0;timelines.push(t);return t},trackTimeline:(opts={})=>{const t=gsap.timeline(opts).pause();timelines.push(t);return t},trackDelayedCall(){throw Error('Unexpected deferred source burst')},document:{getElementById:key=>key==='hud-board-indicator'?indicator:decor},board,canvas};
 vm.createContext(box);vm.runInContext(ts.transpileModule(helpers+'\n'+original,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,box);
 box.options=vm.runInContext('exports.getRegularMerge6FxProfile('+reduced+')',box);box.size=size;
 vm.runInContext(`exports.regularMerge6ShardsTemplated(board,{x:0,y:0},{zIndex:43,density:options.shardDensity,visualScale:options.shardVisualScale,distanceScale:options.shardDistanceScale});`,box);
 const shardLayer=board.children[0],shards=shardLayer.children.map(p=>({points:p.shape.points,rotation:p.rotation,alpha:p.alpha})),shardDraws=draws;
 vm.runInContext(`exports.smokeBubblesAtTile(board,{},size,1.3,{spawnShape:options.smokeSpawnShape,sizeBoostChance:.2,sizeBoostScale:1.3,sizeScale:options.smokeSizeScale,countScale:options.smokeCountScale,instantFadeOut:false,durationScale:.9,distanceScale:options.smokeDistanceScale,ellipseChance:options.smokeEllipseChance,ellipseAspectMin:options.smokeEllipseAspectMin,ellipseAspectMax:options.smokeEllipseAspectMax,color:0xffffff,haloColor:0xffffff,baseAlpha:1,trailAlpha:1,cloudAlphaProfile:true,blendMode:'normal'});`,box);
 const smokeLayer=board.children[1],halo=smokeLayer.children[0],puffNodes=smokeLayer.children.slice(1),puffs=puffNodes.map(p=>({radiusX:p.shape.rx,radiusY:p.shape.ry,rotation:p.rotation,scale:p.scale.x,sx:p.x,sy:p.y})),smokeDraws=draws-shardDraws;
 vm.runInContext('exports.showMultiplierTile(board,{},5,size,1);exports.screenShake({canvas},{strength:Math.round(Math.min(24,10+5*3)*.45),duration:.32,steps:18,ease:"power2.out"});',box);
 const multiplier=board.children[2],samples=[];
 for(const seconds of [0,.017,.051,.097,.153,.249,.361,.479,.631,1]) {timelines.forEach(t=>{if(seconds>=(t._sourceDelay??0))t.totalTime(seconds-(t._sourceDelay??0),false)});samples.push({seconds,shards:shardLayer.children.map(p=>[p.x,p.y,p.alpha]),puffs:puffNodes.map(p=>[p.x,p.y,p.alpha]),halo:halo.alpha*.1,multiplier:[multiplier.scale.x,multiplier.alpha,multiplier.rotation],shake:[canvas.x,canvas.y,indicator.x,indicator.y,decor.x,decor.y]})}
 rows.push({initialShake,depths:[shardLayer.zIndex,smokeLayer.zIndex,multiplier.zIndex],pattern,reduced,size,hot,seed:7+pattern*19+(reduced?41:0)+size,shardDraws,smokeDraws,draws,shards,puffs,samples,ttl});timelines.forEach(t=>t.kill());
}
fs.writeFileSync(out+'ordinary-source-oracle.json',JSON.stringify(rows));gsap.ticker.sleep();console.log('Original FX executed',rows.length,'scenarios',fs.statSync(out+'ordinary-source-oracle.json').size,'bytes');
