import Foundation

nonisolated enum NativeMeterSelectedAudioCatalog {
 static func sources(special:String,variant:String?)->[String]? {
  switch variant ?? special {
  case "wild":return ["./assets/sound/merge 6/merge six obicna.mp3", "./assets/sound/merge 6/merge6 crash.mp3", "./assets/sound/merge 6/merge6 boom.mp3", "./assets/sound/merge 6/stack.mp3", "./assets/sound/Wild and special kockice/star/long_magica_happy_ac_%232-1788980185281.wav", "./assets/sound/Wild and special kockice/star/long_magica_happy_ac_%233-1788980189939.wav", "./assets/sound/Wild and special kockice/star/star1.wav", "./assets/sound/Wild and special kockice/star/star2.wav", "./assets/sound/Wild and special kockice/star/magicle_sparkle_for__%231-1788980027254.wav"]
  case "wild-juice":return ["./assets/sound/Wild and special kockice/juice/bubble.wav", "./assets/sound/Wild and special kockice/juice/introbubble.wav", "./assets/sound/Wild and special kockice/juice/mini2.mp3", "./assets/sound/Wild and special kockice/juice/mini3.wav", "./assets/sound/Wild and special kockice/juice/mini4.wav"]
  case "wild-magnet":return ["./assets/sound/merge 6/merge six obicna.mp3", "./assets/sound/merge 6/merge6 crash.mp3", "./assets/sound/merge 6/merge6 boom.mp3", "./assets/sound/merge 6/stack.mp3", "./assets/sound/magnet pul lforce/boiing.wav"]
  case "wild-tnt":return ["./assets/sound/merge 6/merge six obicna.mp3", "./assets/sound/merge 6/merge6 crash.mp3", "./assets/sound/merge 6/merge6 boom.mp3", "./assets/sound/merge 6/stack.mp3", "./assets/sound/Wild and special kockice/tnt/tnt3.wav", "./assets/sound/Wild and special kockice/tnt/horn.wav", "./assets/sound/Wild and special kockice/tnt/wood break.wav", "./assets/sound/Wild and special kockice/tnt/wood ssplinter.wav", "./assets/sound/Wild and special kockice/tnt/mini crash1.wav", "./assets/sound/mini explozije/mini2.mp3", "./assets/sound/mini explozije/mini3.wav", "./assets/sound/mini explozije/mini4.wav", "./assets/sound/mini explozije/mini5.wav"]
  case "fish":return ["./assets/sound/merge 6/merge six obicna.mp3", "./assets/sound/merge 6/merge6 crash.mp3", "./assets/sound/merge 6/merge6 boom.mp3", "./assets/sound/merge 6/stack.mp3", "./assets/sound/Wild and special kockice/fish/fish0.wav", "./assets/sound/Wild and special kockice/fish/fish1.wav", "./assets/sound/Wild and special kockice/fish/fish2.wav", "./assets/sound/Wild and special kockice/fish/plomp.wav", "./assets/sound/Wild and special kockice/fish/fish speaks.wav"]
  case "kanta":return ["./assets/sound/merge 6/merge six obicna.mp3", "./assets/sound/merge 6/merge6 crash.mp3", "./assets/sound/merge 6/merge6 boom.mp3", "./assets/sound/merge 6/stack.mp3", "./assets/sound/Wild and special kockice/kanta/tup.wav", "./assets/sound/Wild and special kockice/kanta/spacesound.wav", "./assets/sound/Wild and special kockice/kanta/bibis.wav", "./assets/sound/Wild and special kockice/kanta/kanta4.wav", "./assets/sound/Wild and special kockice/kanta/kanta1.wav", "./assets/sound/Wild and special kockice/kanta/kanta2.wav", "./assets/sound/Wild and special kockice/kanta/kanta3.wav", "./assets/sound/Wild and special kockice/kanta/hodanje.wav"]
  case "bee":return ["./assets/sound/merge 6/merge six obicna.mp3", "./assets/sound/merge 6/merge6 crash.mp3", "./assets/sound/merge 6/merge6 boom.mp3", "./assets/sound/merge 6/stack.mp3", "./assets/sound/Wild and special kockice/bee/bee start.wav", "./assets/sound/Wild and special kockice/bee/BEE.wav", "./assets/sound/Wild and special kockice/bee/brushing.wav", "./assets/sound/Wild and special kockice/bee/happy bee.wav"]
  case "laser-gun":return ["./assets/sound/Wild and special kockice/tnt/mini crash1.wav", "./assets/sound/mini explozije/mini2.mp3", "./assets/sound/mini explozije/mini3.wav", "./assets/sound/mini explozije/mini4.wav", "./assets/sound/mini explozije/mini5.wav", "./assets/sound/Wild and special kockice/tnt/horn.wav", "./assets/sound/Wild and special kockice/gun/prep.wav", "./assets/sound/Wild and special kockice/gun/priprema.wav", "./assets/sound/Wild and special kockice/gun/beam1.wav", "./assets/sound/Wild and special kockice/gun/beam2.wav", "./assets/sound/Wild and special kockice/gun/plombing.wav", "./assets/sound/Wild and special kockice/star/star1.wav"]
  case "spaceship":return ["./assets/sound/Wild and special kockice/spaceship/crash.wav", "./assets/sound/Wild and special kockice/spaceship/crash2.wav", "./assets/sound/Wild and special kockice/spaceship/ulazak.wav", "./assets/sound/Wild and special kockice/spaceship/abduction.wav", "./assets/sound/Wild and special kockice/spaceship/hi pitch beam.wav", "./assets/sound/Wild and special kockice/spaceship/sucking.wav", "./assets/sound/Wild and special kockice/spaceship/materijal.wav", "./assets/sound/Wild and special kockice/spaceship/suck beam.wav", "./assets/sound/Wild and special kockice/spaceship/odlazak.wav", "./assets/sound/merge 6/merge six obicna.mp3", "./assets/sound/merge 6/merge6 crash.mp3", "./assets/sound/merge 6/merge6 boom.mp3", "./assets/sound/merge 6/stack.mp3", "./assets/sound/magnet pul lforce/boiing.wav"]
  case "bottle":return ["./assets/sound/Wild and special kockice/bottle/water waves.wav", "./assets/sound/Wild and special kockice/bottle/bottle1.wav", "./assets/sound/Wild and special kockice/bottle/bottle 2.wav", "./assets/sound/Wild and special kockice/bottle/cling.wav", "./assets/sound/Wild and special kockice/bottle/cling2.wav", "./assets/sound/Wild and special kockice/bottle/bublesi.wav", "./assets/sound/Wild and special kockice/bottle/bubsplat1.wav", "./assets/sound/Wild and special kockice/bottle/bubsplat2.wav", "./assets/sound/Wild and special kockice/bottle/glass crack.wav", "./assets/sound/merge 6/merge six obicna.mp3", "./assets/sound/merge 6/merge6 crash.mp3", "./assets/sound/merge 6/merge6 boom.mp3", "./assets/sound/merge 6/stack.mp3", "./assets/sound/magnet pul lforce/boiing.wav"]
  case "honey":return ["./assets/sound/merge 6/merge six obicna.mp3", "./assets/sound/merge 6/merge6 crash.mp3", "./assets/sound/merge 6/merge6 boom.mp3", "./assets/sound/merge 6/stack.mp3", "./assets/sound/magnet pul lforce/boiing.wav", "./assets/sound/Wild and special kockice/honey/honeysplat.wav", "./assets/sound/Wild and special kockice/honey/hapr.wav", "./assets/sound/Wild and special kockice/honey/supersplat.wav", "./assets/sound/Wild and special kockice/honey/BEES3s.wav"]
  case "flower":return ["./assets/sound/Wild and special kockice/tnt/mini crash1.wav", "./assets/sound/mini explozije/mini2.mp3", "./assets/sound/mini explozije/mini3.wav", "./assets/sound/mini explozije/mini4.wav", "./assets/sound/mini explozije/mini5.wav", "./assets/sound/merge 6/merge six obicna.mp3", "./assets/sound/merge 6/merge6 crash.mp3", "./assets/sound/merge 6/merge6 boom.mp3", "./assets/sound/merge 6/stack.mp3", "./assets/sound/Wild and special kockice/flower/bush0.wav", "./assets/sound/Wild and special kockice/flower/bush2.wav", "./assets/sound/Wild and special kockice/flower/bush3.wav", "./assets/sound/Wild and special kockice/flower/boom.wav", "./assets/sound/Wild and special kockice/flower/leaves.wav", "./assets/sound/Wild and special kockice/flower/spark.wav"]
  case "barell":return ["./assets/sound/Wild and special kockice/tnt/mini crash1.wav", "./assets/sound/mini explozije/mini2.mp3", "./assets/sound/mini explozije/mini3.wav", "./assets/sound/mini explozije/mini4.wav", "./assets/sound/mini explozije/mini5.wav", "./assets/sound/Wild and special kockice/barell/tnt3.wav", "./assets/sound/Wild and special kockice/barell/horn.wav", "./assets/sound/Wild and special kockice/barell/wood break.wav", "./assets/sound/Wild and special kockice/barell/wood ssplinter.wav", "./assets/sound/Wild and special kockice/barell/puf1.wav", "./assets/sound/Wild and special kockice/barell/puf2.wav", "./assets/sound/Wild and special kockice/barell/planks.wav", "./assets/sound/Wild and special kockice/barell/poof.wav", "./assets/sound/merge 6/merge six obicna.mp3", "./assets/sound/merge 6/merge6 crash.mp3", "./assets/sound/merge 6/merge6 boom.mp3", "./assets/sound/merge 6/stack.mp3"]
  case "mushroom":return []
  case "robo-cube":return ["./assets/sound/Wild and special kockice/robo/bibiribi.wav", "./assets/sound/Wild and special kockice/robo/robo1.wav", "./assets/sound/Wild and special kockice/robo/outro zing.wav"]
  case "cubero":return []
  case "beach-ball":return ["./assets/sound/merge 6/merge six obicna.mp3", "./assets/sound/merge 6/merge6 crash.mp3", "./assets/sound/merge 6/merge6 boom.mp3", "./assets/sound/merge 6/stack.mp3", "./assets/sound/Wild and special kockice/ball/ball1.wav", "./assets/sound/Wild and special kockice/ball/ball2.wav", "./assets/sound/Wild and special kockice/ball/ball4.wav", "./assets/sound/Wild and special kockice/ball/ball5-60pct.wav", "./assets/sound/Wild and special kockice/ball/ball impact.mp3", "./assets/sound/Wild and special kockice/tnt/mini crash1.wav", "./assets/sound/mini explozije/mini2.mp3", "./assets/sound/mini explozije/mini3.wav", "./assets/sound/mini explozije/mini4.wav", "./assets/sound/mini explozije/mini5.wav"]
  default:return nil
  }
 }
}
