// Execute preserved owners; only the DOM/Pixi containers are replaced with data objects.
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const repo=fileURLToPath(new URL('../../',import.meta.url)),require=createRequire(import.meta.url);
const ts=require(repo+'node_modules/typescript');
const core=fs.readFileSync(repo+'src/modules/app-core.ts','utf8'),hud=fs.readFileSync(repo+'src/modules/hud-helpers.ts','utf8');
const coreStart=core.indexOf('  const TOP_PAD   ='),coreEnd=core.indexOf('  // Scale board to fit screen width',coreStart);
const layoutStart=hud.indexOf('  if (!HUD_ROOT) return;',hud.indexOf('export function layout(')),layoutEnd=hud.indexOf('  // labeli',layoutStart);
const meterStart=hud.indexOf('    wild.view.x = SIDE;',layoutEnd),meterEnd=hud.indexOf('  }',meterStart);
if([coreStart,coreEnd,layoutStart,layoutEnd,meterStart,meterEnd].some(x=>x<0))throw Error('Original source owner extraction failed');
const program=`function sample(){${core.slice(coreStart,coreEnd)}\n{const top=safeTop;${hud.slice(layoutStart,layoutEnd)}\nconst barW=Math.max(120,vw-2*SIDE);${hud.slice(meterStart,meterEnd)}\nreturn {hudTop:safeTop,valueRowY:vh-safeTop-yValue,meter:[wild.view.x,vh-safeTop-wild.view.y-10,wild.width,10]};}}sample();`;
const js=ts.transpileModule(program,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
const cases=[];
for(const [width,height]of[[320,568],[390,844],[430,932],[844,390],[768,1024],[1024,768],[1512,982]])for(const safeTop of [0,20,44,47,59]){
 const wild={view:{},setWidth(v){this.width=v}};
 const box={vw:width,vh:height,adjustedSAT:safeTop,SAB:34,isMobilePortrait:height>width,HUD_H:60,__hudMetrics:{},devLog(){},HUD_ROOT:{},app:{renderer:{width,height}},boardText:{style:{fontSize:24}},scoreText:{style:{fontSize:18}},comboText:{style:{fontSize:18}},wild};
 vm.createContext(box);const actual=vm.runInContext(js,box);cases.push({width,height,safeTop,...actual});
}
const target=repo+'native/standalone/Stack to SixTests/NativeGameplayChromeSourceOracle.swift';
fs.writeFileSync(target,`// Generated by scripts/native-oracles/gameplay-chrome.mjs from actual TS owners.\nimport Foundation\nenum NativeGameplayChromeSourceOracle {\n static let json = #"""\n${JSON.stringify(cases)}\n"""#\n}\n`);
console.log('Executed original gameplay HUD owners:',cases.length,'viewport/safe-area cases.');
